import 'package:flutter/material.dart';

import '../../core/icons/sw_icon.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_spacing.dart';
import '../../core/theme/app_typography.dart';
import '../../core/widgets/sw_screen.dart';
import '../../core/widgets/sw_widgets.dart';
import '../../data/app_state.dart';
import '../../data/mock_data.dart';
import '../../data/models.dart';
import '../stylist/style_avatar_screen.dart';

/// Frame 13 - detailed breakdown of the recommended combination.
///
/// When an [outfit] generated by the backend is supplied, the piece grid,
/// score ring and factor bars render its live compatibility report
/// (`POST /ai/calculate-compatibility`); otherwise the bundled breakdown
/// is shown.
class PerfectMatchScreen extends StatefulWidget {
  const PerfectMatchScreen({super.key, this.outfit});

  final Outfit? outfit;

  @override
  State<PerfectMatchScreen> createState() => _PerfectMatchScreenState();
}

class _PerfectMatchScreenState extends State<PerfectMatchScreen> {
  List<({String label, int value})>? _breakdown;
  List<ClothingItem>? _pieces;

  @override
  void initState() {
    super.initState();
    _resolve();
  }

  Future<void> _resolve() async {
    final outfit = widget.outfit;
    if (outfit == null) return;
    // Resolve piece images from the live wardrobe.
    final ids = outfit.itemIds ?? const <String>[];
    if (ids.isNotEmpty) {
      final wardrobe = AppState.instance.wardrobe;
      final found = [
        for (final id in ids)
          ...wardrobe.where((w) => w.id == id),
      ];
      if (found.isNotEmpty && mounted) setState(() => _pieces = found);
    }
    if (outfit.breakdown != null && outfit.breakdown!.isNotEmpty) {
      if (mounted) setState(() => _breakdown = outfit.breakdown);
      return;
    }
    if (ids.length >= 2) {
      final compat = await AppState.instance.compatibility(ids);
      if (!mounted) return;
      final rows = (compat?['breakdown'] as List?) ?? [];
      if (rows.isNotEmpty) {
        setState(() {
          _breakdown = [
            for (final b in rows)
              (
                label: '${b['label'] ?? ''}',
                value: (b['value'] ?? 0).toInt(),
              ),
          ];
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final outfit = widget.outfit;
    final breakdown = _breakdown ??
        outfit?.breakdown ??
        (outfit == null ? MockData.matchBreakdown : null) ??
        MockData.matchBreakdown;
    final pieces = _pieces ?? MockData.perfectMatchPieces;
    final match = outfit?.match ?? 92;
    final why = outfit?.explanation ??
        'These pieces work well together because the neutral '
            'colors create a balanced look and the casual style '
            "matches your university occasion.";

    return SwScreen(
      scroll: true,
      padding: const EdgeInsets.only(bottom: Insets.xxl),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const SwAppBar(title: 'Perfect Match'),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: Insets.gutter),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                SwCard(
                  padding: const EdgeInsets.all(Insets.lg),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        "TODAY'S FLATLAY SUGGESTION",
                        style: AppText.overline,
                      ),
                      const SizedBox(height: Insets.md),
                      _PieceGrid(
                        images: [
                          for (final p in pieces) p.image,
                        ],
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: Insets.lg),
                _ScoreCard(match: match),
                const SizedBox(height: Insets.xl),
                Text('AI Breakdown Analysis', style: AppText.h4),
                const SizedBox(height: Insets.md),
                SwCard(
                  padding: const EdgeInsets.symmetric(
                    horizontal: Insets.lg,
                    vertical: Insets.lg,
                  ),
                  child: Column(
                    children: [
                      for (final row in breakdown) ...[
                        _ScoreBar(label: row.label, value: row.value),
                        if (row != breakdown.last)
                          const SizedBox(height: Insets.lg),
                      ],
                    ],
                  ),
                ),
                const SizedBox(height: Insets.lg),
                SwBanner(
                  icon: SwIcon.sparkle,
                  title: 'WHY THIS OUTFIT?',
                  message: why,
                ),
                const SizedBox(height: Insets.xl),
                SwButton(
                  label: 'Save Outfit',
                  onTap: () async {
                    final ok = outfit?.itemIds?.isNotEmpty == true
                        ? await AppState.instance.api
                            .createOutfit(
                              outfit!.name,
                              outfit.itemIds!,
                              occasion: outfit.occasion,
                            )
                            .then((_) => true)
                            .catchError((_) => false)
                        : true;
                    if (!context.mounted) return;
                    ScaffoldMessenger.of(context)
                      ..hideCurrentSnackBar()
                      ..showSnackBar(
                        SnackBar(
                          content: Text(
                            ok
                                ? 'Outfit saved.'
                                : 'Backend offline — try again shortly.',
                          ),
                        ),
                      );
                  },
                ),
                const SizedBox(height: Insets.md),
                SwOutlineButton(
                  label: 'Preview on Avatar',
                  onTap: () => Navigator.of(context).push(
                    MaterialPageRoute(
                      builder: (_) => const StyleAvatarScreen(),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// Two by two grid of the garments in the recommendation.
class _PieceGrid extends StatelessWidget {
  const _PieceGrid({required this.images});

  final List<String> images;

  @override
  Widget build(BuildContext context) {
    return GridView.builder(
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      itemCount: images.length,
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        mainAxisSpacing: Insets.md,
        crossAxisSpacing: Insets.md,
        childAspectRatio: 1.05,
      ),
      itemBuilder: (context, i) {
        return SwProductImage(image: images[i], radius: Radii.md);
      },
    );
  }
}

/// Ring gauge plus the confidence copy.
class _ScoreCard extends StatelessWidget {
  const _ScoreCard({required this.match});

  final int match;

  @override
  Widget build(BuildContext context) {
    return SwCard(
      padding: const EdgeInsets.all(Insets.lg),
      child: Row(
        children: [
          SizedBox.square(
            dimension: 72,
            child: CustomPaint(
              painter: _RingPainter(match / 100),
              child: Center(
                child: Text(
                  '$match%',
                  style: AppText.numeric.copyWith(fontSize: 18),
                ),
              ),
            ),
          ),
          const SizedBox(width: Insets.lg),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Compatibility Score', style: AppText.cardTitle),
                const SizedBox(height: 4),
                Text(
                  "This combo is tailored optimally for tomorrow's weather "
                  '& university event.',
                  style: AppText.caption,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// Circular progress ring used for the compatibility score.
class _RingPainter extends CustomPainter {
  const _RingPainter(this.value);

  final double value;

  @override
  void paint(Canvas canvas, Size size) {
    const stroke = 6.0;
    final rect = Offset.zero & size;

    canvas.drawArc(
      rect.deflate(stroke / 2),
      0,
      6.28318,
      false,
      Paint()
        ..style = PaintingStyle.stroke
        ..strokeWidth = stroke
        ..color = AppColors.border,
    );
    canvas.drawArc(
      rect.deflate(stroke / 2),
      -1.5708,
      6.28318 * value,
      false,
      Paint()
        ..style = PaintingStyle.stroke
        ..strokeWidth = stroke
        ..strokeCap = StrokeCap.round
        ..color = AppColors.primary,
    );
  }

  @override
  bool shouldRepaint(_RingPainter old) => old.value != value;
}

class _ScoreBar extends StatelessWidget {
  const _ScoreBar({required this.label, required this.value});

  final String label;
  final int value;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Expanded(child: Text(label, style: AppText.body)),
            Text('$value%', style: AppText.bodyStrong.copyWith(fontSize: 13)),
          ],
        ),
        const SizedBox(height: 6),
        ClipRRect(
          borderRadius: Radii.pillRadius,
          child: LinearProgressIndicator(
            value: value / 100,
            minHeight: 5,
            backgroundColor: AppColors.border,
            valueColor: const AlwaysStoppedAnimation(AppColors.primary),
          ),
        ),
      ],
    );
  }
}
