import 'package:flutter/material.dart';

import '../../core/icons/sw_icon.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_spacing.dart';
import '../../core/theme/app_typography.dart';
import '../../core/widgets/sw_screen.dart';
import '../../core/widgets/sw_widgets.dart';
import '../../data/app_state.dart';
import '../../data/models.dart';

/// Frame 19 - capsule wardrobe builder for a trip.
///
/// The packing list is generated by the backend (`POST /travel/packing-list`).
class TravelPlannerScreen extends StatefulWidget {
  const TravelPlannerScreen({super.key});

  @override
  State<TravelPlannerScreen> createState() => _TravelPlannerScreenState();
}

class _TravelPlannerScreenState extends State<TravelPlannerScreen> {
  final _state = AppState.instance;
  final Set<int> _packed = {for (var i = 0; i < 8; i++) i};
  bool _generating = false;

  @override
  void initState() {
    super.initState();
    _state.loadPacking();
  }

  Future<void> _generate() async {
    setState(() => _generating = true);
    await _state.loadPacking(destination: 'Istanbul', days: 7);
    if (!mounted) return;
    setState(() {
      _generating = false;
      _packed.addAll(
        {for (var i = 0; i < _state.packingItems.length; i++) i},
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return ListenableBuilder(
      listenable: _state,
      builder: (context, _) {
        final items = _state.packingItems;
        final groups = _groupsFor(items.length);
        return SwScreen(
          scroll: true,
          padding: const EdgeInsets.only(bottom: Insets.xxl),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Padding(
                padding: const EdgeInsets.fromLTRB(
                  Insets.gutter,
                  Insets.sm,
                  Insets.gutter,
                  0,
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('Travel Planner', style: AppText.h1),
                          const SizedBox(height: 2),
                          Text(
                            'A capsule wardrobe curated for your trip',
                            style: AppText.caption,
                          ),
                        ],
                      ),
                    ),
                    const SwIconButton(icon: SwIconButtonKind.bag),
                  ],
                ),
              ),
              const SizedBox(height: Insets.lg),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: Insets.gutter),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Row(
                      children: [
                        Expanded(
                          child: _TripField(
                            label: 'DESTINATION',
                            value: 'Istanbul, TR',
                          ),
                        ),
                        SizedBox(width: Insets.md),
                        Expanded(
                          child:
                              _TripField(label: 'DATES', value: 'Oct 5 - 12'),
                        ),
                      ],
                    ),
                    const SizedBox(height: Insets.md),
                    const _ForecastStrip(),
                    const SizedBox(height: Insets.lg),
                    SwButton(
                      label: _generating
                          ? 'Generating…'
                          : 'Generate Packing List',
                      onTap: _generate,
                    ),
                    const SizedBox(height: Insets.md),
                    SwBanner(
                      icon: SwIcon.sparkle,
                      message: _state.packingMessage,
                    ),
                    const SizedBox(height: Insets.lg),
                    for (final (group, indices) in groups) ...[
                      Text('$group (${indices.length})', style: AppText.h4),
                      const SizedBox(height: Insets.md),
                      _PackingRow(
                        entries: [
                          for (final i in indices)
                            if (i < items.length)
                              PackingEntry(
                                name: items[i].name,
                                image: items[i].image,
                                packed: _packed.contains(i),
                              ),
                        ],
                      ),
                      const SizedBox(height: Insets.lg),
                    ],
                  ],
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  /// Splits the live packing list into the same 2-per-row groups.
  static List<(String, List<int>)> _groupsFor(int length) {
    const names = ['Tops', 'Bottoms', 'Shoes', 'Accessories'];
    final groups = <(String, List<int>)>[];
    var i = 0, g = 0;
    while (i < length) {
      final take = (i + 2 <= length) ? 2 : length - i;
      groups.add((g < names.length ? names[g] : 'More', [
        for (var k = 0; k < take; k++) i + k,
      ]));
      i += take;
      g++;
    }
    return groups;
  }
}

class _TripField extends StatelessWidget {
  const _TripField({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(Insets.md),
      decoration: BoxDecoration(
        color: AppColors.surface,
        borderRadius: Radii.tileRadius,
        border: Border.all(color: AppColors.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label, style: AppText.overline.copyWith(fontSize: 9)),
          const SizedBox(height: 3),
          Text(
            value,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
            style: AppText.bodyStrong.copyWith(fontSize: 13),
          ),
        ],
      ),
    );
  }
}

/// Warm forecast banner inside the travel flow.
class _ForecastStrip extends StatelessWidget {
  const _ForecastStrip();

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(Insets.md),
      decoration: BoxDecoration(
        color: AppColors.travelTint,
        borderRadius: Radii.tileRadius,
      ),
      child: Row(
        children: [
          const SwIconView(
            SwIcon.sun,
            size: 16,
            color: AppColors.sun,
            strokeWidth: 1.8,
          ),
          const SizedBox(width: Insets.md),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Sunny • 24°C - 28°C', style: AppText.bodyStrong),
                Text('Perfect lightweight weather', style: AppText.caption),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// Two column list of packed garments with a checkmark toggle.
class _PackingRow extends StatelessWidget {
  const _PackingRow({required this.entries});

  final List<PackingEntry> entries;

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        for (var i = 0; i < entries.length; i++) ...[
          if (i > 0) const SizedBox(width: Insets.md),
          Expanded(child: _PackingCell(entry: entries[i])),
        ],
      ],
    );
  }
}

class _PackingCell extends StatelessWidget {
  const _PackingCell({required this.entry});

  final PackingEntry entry;

  @override
  Widget build(BuildContext context) {
    return SwCard(
      padding: const EdgeInsets.all(Insets.sm),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            height: 52,
            width: double.infinity,
            child: SwProductImage(image: entry.image, radius: Radii.sm),
          ),
          const SizedBox(height: Insets.sm),
          Text(
            entry.name,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
            style: AppText.labelStrong.copyWith(fontSize: 11),
          ),
          const SizedBox(height: 2),
          Row(
            children: [
              const SwIconView(
                SwIcon.check,
                size: 11,
                color: AppColors.success,
                strokeWidth: 2.4,
              ),
              const SizedBox(width: 3),
              Text(
                'Packed',
                style: AppText.caption.copyWith(
                  fontSize: 10,
                  color: AppColors.success,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
